#!/usr/bin/env python

from flask.ext.script import Manager, Server
from flask.ext.assets import ManageAssets

from hbtest import app

manager = Manager(app)
manager.add_command('assets', ManageAssets())
manager.add_command('runserver', Server(host='0.0.0.0', port=12345))


if __name__ == "__main__":
    manager.run()
